# Generated by Django 3.0.3 on 2021-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='image_specie',
        ),
    ]
