# Generated by Django 3.0.3 on 2021-05-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0002_auto_20210516_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='taxon_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
