# Generated by Django 3.2 on 2021-05-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0003_auto_20210518_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markers',
            old_name='specie',
            new_name='specie_id',
        ),
        migrations.RenameField(
            model_name='markers',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='markers',
            name='specie_id',
            field=models.ForeignKey(db_column='specie_id', on_delete=django.db.models.deletion.CASCADE, to='species_app.species'),
        ),
        migrations.AlterField(
            model_name='markers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='species_app.users'),
        ),
    ]
