# Generated by Django 3.0.3 on 2021-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0003_auto_20210518_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='taxon_id',
            field=models.CharField(max_length=25),
        ),
    ]
